### ISSUE TITLE
My project may help you figure out what you need.

### ISSUE THREAD

**Issue by AppliedEllipsis** [UKY-CS-499-Project14-Spring17/UKY-CS-499-Project14-Spring17.github.io#5]
Greetings, I saw your project and git page and thought that my project may help you solve some of your issues or unknowns. I just got one of these and decided to RE it a few days ago. It's still a work in progress, but has nearly every protocol function including a few ways start doing actual cnc vector stuff, which can be faster, depending on the use case.

If you use parts or concepts from my code, just put a shout out to me.
If you have any questions, feel free to reach out to me.

https://github.com/AppliedEllipsis/pyLaser

Happy RE

**Comment by gps1784** [comment]
Closing: see my response @ UKY-CS-499-Project14-Spring17/htpewpew#2
